# Generated by Django 4.1.7 on 2023-07-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(default=None, upload_to="", verbose_name="썸네일"),
            preserve_default=False,
        ),
    ]
